# Site
repository: tommasorigon/tommasorigon.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Tommaso Rigon
title: Researcher Associate at Duke University
email: tommaso.rigon@gmail.com

# Social links
github_username:  tommasorigon
linkedin_username: tommasorigon

#Orcid_username: https://orcid.org/0000-0002-9224-543X

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Welcome to my website! My name is **Tommaso Rigon** and I am a **Research Associate in Statistics** at Duke University.

    In this website you can find my [complete curriculum vitae](/files/cv_Rigon.pdf) and the list of my publications.

    My research interests include: applied Bayesian modeling, Bayesian clustering, Bayesian nonparametrics, computational statistics, functional data analysis.

    I have also a [GitHub](https://github.com/tommasorigon) profile and a [Google scholar](https://scholar.google.it/citations?user=vRRVHqgAAAAJ&hl=en) account.

#For more, download my [curriculum vitae](/files/cv_Rigon.pdf).

#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://#foobar.com) and highlight things <mark>like this</mark>.

#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - Lists
#    - Tables
#    - Links
#    - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Service to profession Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
    * Elected member of the board (2016-2018) of the [young group of the Italian Statistical Society](https://youngsis.github.io) (ySIS)

    * Referee for: Annals of Statistics, Bayesian Analysis, Computational Statistics and Data Analysis, Electronic Journal of Statistics, European Journal of Operational Research, Journal of Computational and Graphical Statistics, Statistical Methods & Applications, Statistics & Probability Letters, Social Indicators Research.
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

# Analytics
analytics:
  provider               :  "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-107301343-1"
