# Site
repository: tommasorigon/tommasorigon.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Tommaso Rigon
title: Research Associate at Duke University
email: tommaso.rigon@gmail.com

# Social links
github_username:  tommasorigon
linkedin_username: tommasorigon
twitter_username: RigonTommaso

# About Section
about_title: About Me
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    I am a Research Associate in Statistics at the [department of Statistical Science](https://stat.duke.edu) of [Duke University](https://www.duke.edu). I currently live in [Durham](https://g.page/DukeUniv?share), a city in North Carolina, USA.

    My [<mark>complete curriculum vitae</mark>](/files/cv_Rigon.pdf) is available at [this link](/files/cv_Rigon.pdf). For more information about myself, you can also visit my [GitHub](https://github.com/tommasorigon) and [Google scholar](https://scholar.google.it/citations?user=vRRVHqgAAAAJ&hl=en) profiles.

    I am interested in Bayesian methods for the analysis of complex data, covering the theoretical, applicative, and computational aspects. I try to balance these three macro-areas in my research. During my Ph.D. at [Bocconi University](https://www.unibocconi.eu/) I studied novel methods to approximate Bayesian nonparametric priors, which are flexible and increasingly popular probabilistic tools.  I also developed Bayesian models for marketing segmentation and for the analysis of fMRI data. Moreover, I am intrigued by the computational aspects of Bayesian statistics, including Markov chain Monte Carlo and variational approaches. For instance, part of my work is based on the Polya-gamma data-augmentation and its algorithmical implications.

# Projects Section
projects_title: Academic Positions

# Experience Section
experience_title: Professional Experience

# Education Section
education_title: Education

# More Section
talks_title: Talks and conferences
talks_content: |
    ciao

# More Section
more_title: Publications
more_content: |

    **Articles in refereed journals**

    1. Durante, D. and **Rigon, T.** (2019). Conditionally conjugate mean-field variational Bayes for logistic models, *Statistical Science*. **34**(3), 472--485. [[Link]](https://projecteuclid.org/euclid.ss/1570780980) [[GitHub Repository]](https://github.com/tommasorigon/logisticVB).

    1. **Rigon, T.**, Durante, D. and Torelli, N. (2019). Bayesian semiparametric modelling of contraceptive behavior in India via sequential logistic regressions, *Journal of the Royal Statistical Society, Series A* **182**(1), 225--247. [[Link]](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssa.12361) [[GitHub Repository]](https://github.com/tommasorigon/India-SequentiaLogit).

    1. Durante, D., Canale, A. and **Rigon, T.** (2019).  A nested expectation-maximization algorithm for latent class models with covariates, *Statistics and Probability Letters* **146**, 97--103. [[Link]](https://www.sciencedirect.com/science/article/pii/S0167715218303390)  [[GitHub Repository]](https://github.com/danieledurante/nEM).

    **Submitted and working papers**

    1. **Rigon, T.** and Durante, D., (2019+), Tractable Bayesian density regression via logit stick-breaking priors, *arXiv:1701.02969*. Under review. [[ArXiv]](https://arxiv.org/abs/1701.02969) [[GitHub Repository]](https://github.com/tommasorigon/LSBP).

    1. Lijoi, A., Pr端nster, I. and **Rigon, T.** (2019+). Sampling hierarchies of discrete random structures. Under review.

    1. Lijoi, A., Pr端nster, I. and **Rigon, T.** (2019+). The Pitman--Yor multinomial process for mixture modeling. Under review.

    1. **Rigon, T.** (2019+). An enriched mixture model for functional clustering. Submitted.  [[ArXiv]](https://arxiv.org/abs/1907.02493).

    1. Lijoi, A., Pr端nster, I. and **Rigon, T.** (2019+). Finite-dimensional discrete random structures and Bayesian clustering. Submitted.

    **Refereed conference proceedings, publications in monographs, discussions**

    1. Aliverti, E., Paganin, S., **Rigon, T.** and Russo, M. (2019+). A discussion on: ``Latent nested nonparametric priors'' by Camerlenghi, F., Dunson, D.B., Lijoi, A., Pr端nster, I. and Rodriguez, A. in *Bayesian Analysis* (In press).

    1. **Rigon, T.** (2018). Logit stick-breaking priors for partially exchangeable count data. In *Book of Short Papers SIS 2018* (Abbruzzo, A., Piacentino, D., Chiodi, M., and Brentari, E., editors). ISBN: 9788891910233. [[Link]](https://it.pearson.com/content/dam/region-core/italy/pearson-italy/pdf/Docenti/ISTITUZIONI%20-%20HE%20-%20PDF%20-%20SIS%20V2.pdf).

    1. Caponera, A., Denti, F., **Rigon, T.**, Sottosanti, A. and Gelfand, A. (2018). Hierarchical Spatio-Temporal Modeling of Resting State fMRI Data. In *Studies in Neural Data Science* (Canale, A., Durante, D., Paci, L., Scarpa, B., editors). [[Link]](https://www.springer.com/us/book/9783030000387) [[GitHub Repository]](https://github.com/tommasorigon/StartUpResearch).

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]

# Analytics
analytics:
  provider               :  "google" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-107301343-1"
